"""
    Name: Kaushik S Kalmady
    Date: 8/10/2017

    Demo of RFI mitigation using UNet
    HIDE and SEEK packages are used for simulating and generating data and
    groundtruths

    Follow instructions in process_data.py, and training_unet.py and run them
    before you run this script.
    This code requires the cpkt files generated by that script.


    You will also need to have tf_unet installed.
    For installation instructions: tf_unet.readthedocs.io


"""


from __future__ import division, print_function
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import glob
import os
from scripts.radio_util import DataProvider
from tf_unet import unet


def load_data():
    """
    Returns the Bleien Survery data and the HIDE simulated data after loading
    them separately
    """

    # You can use two dataproviders for each path
    # Define Bleien data files path
    bleien_path = ""
    hide_path = ""

    # Load data file names
    bleien_files = glob.glob(bleien_path)
    hide_files = glob.glob(hide_path)

    # Define data_providers
    bleien_data_provider =
    hide_data_provider =

    # Load data using two dataproviders
    # _ is used for variables we don't want
    bleien_data, _ =
    hide_data, _ =

    return bleien_data, hide_data


def display_side_by_side(first, second):
    """
    Display two tod data side by side

    parameters
    ===========
    first : first data variable
    second : second data variable'

    """

    fig, ax =

    # plot first and second data as in visual.py

    plt.show()


def load_and_predict(data):
    """
    Return UNet predicted output and SEEK's sum_threshold output (check RFI
    mitigation page in SEEK docs)

    """

    # Define Unet
    unet =


    # Path to cpkt file of trained Unet
    path = ""

    # Predict using Unet
    unet_predict =

    # Predict using SEEK's sum_threshold
    seek_predict =

    return unet_predict, seek_predict


if __name__ == "__main__":

    # Load both bleien data and hide data
    bleien_data, hide_data = load_data()

    # Visualise both data
    # This is to show that both the data are pretty similar
    display_side_by_side(bleien_data, hide_data)

    # Make predicitons on the hide data
    unet_predict, seek_predict = load_and_predict(hide_data)

    # Display results
    display_side_by_side(unet_predict, seek_predict)
