"""
    Name: Rahul Sankar, Kaushik S Kalmady
    Date: 7/10/2017
    Ref : https://github.com/jakeret/tf_unet/blob/master/demo/demo_radio_data.ipynb
    Generating single dish radio telescope data using the HIDE package and visualizing it.
    For installation instructions of the HIDE package: hide.readthedocs.io, https://github.com/cosmo-ethz/hide
"""
from __future__ import print_function
import matplotlib.pyplot as plt
import matplotlib
import os
import h5py


# Generates data using HIDE
# We can adjust the 'strategy-start' and 'strategy-end' arguments to control how much data we want to generate
# The default is set to one day 
# os.system("hide --strategy-start=2016-03-21-00:00:00 --strategy-end=2016-03-21-23:59:00 --verbose=True hide.config.bleien7m")

# To visualize the data generated by HIDE

# Make a directory to store the visualizations
os.makedirs("hide_visualization")

# Navigate to the directory
os.chdir("hide_visualization/")

# Export visualization of the generated data
# For some reason it skips over certain files but you get enough images to get a feel of what the data is
indir = '../2016/03/21'
for root, dirs, filenames in os.walk(indir):
    for f in filenames:
        try:
            with h5py.File(os.path.join(root, f), "r") as fp:
                 tod = fp["P/Phase1"].value
                 time = fp["TIME"].value
            fig = plt.figure()
            plt.imshow(tod, aspect="auto", extent=(time[0], time[-1],990, 1260), cmap="gist_earth", norm=matplotlib.colors.LogNorm())
            plt.colorbar()
            name = f + ".png"
            fig.savefig(name)
            plt.close(fig)   
        except IOError:
            pass


print("\nDone. Check 2016/03/21 for generateed .h5 files and hide_visualization for the images")
